{
 "title": "logs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "UI service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"ui-deployment\"}"
    }
   ]
  },
  {
   "title": "Graph service logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"graph-deployment\"}"
    }
   ]
  },
  {
   "title": "Backend Service Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"backend-deployment\"}"
    }
   ]
  }
 ]
}